### ISSUE TITLE
Kindly add /list command

### ISSUE THREAD

**Issue by rahilarious** [emacs-circe/circe#407]

**Comment by wasamasa** [comment]
Just use `/quote list` if you want to actually use the command. Note that it's a bad idea to do this because the output of the command can be massive and Circe will be so busy processing it all that it may not reply to the keepalive ping commands and ends up disconnecting from the network as a result.

For this reason, networks affected by this issue recommend either:

- Using `/list` with modifiers to limit the output. Try `/quote help list` for further info on network-specific modifiers, such as `/quote list *pattern*`
- Using a network-specific service such as alis on Libera.chat. Try `/msg alis help list` and `/msg alis list pattern`.

I don't expect to fix the throughput issue any time soon due to the design of Circe. It uses one network process with a sentinel processing incoming input. If it's busy with `/list` output, it is bound to reply late to any incoming `PING`.

What I could do is introduce a dummy command pointing out the above gotchas or even change the output for unknown commands to suggest trying the `/quote` command. What do you think?

**Comment by Thaodan** [comment]
> * 
> 
> 
> I don't expect to fix the throughput issue any time soon due to the design of Circe. It uses one network process with a sentinel processing incoming input. If it's busy with `/list` output, it is bound to reply late to any incoming `PING`.

Can this be changed? The issue also affects other situations e.g. when other modes are doing something and block the ui.

**Comment by wasamasa** [comment]
There are very specific workarounds, such as using several processes and waiting for either of them to be ready for processing. That's a crutch for Emacs being ultimately single-threaded and packages expecting this kind of design. So no, there is no generic solution, short of a complete Emacs redesign.
